// generated by "charlatan -dir=testdata/pointer -output=testdata/pointer/pointer.go Pointer".  DO NOT EDIT.

package main

import "reflect"

// PointerPointInvocation represents a single call of FakePointer.Point
type PointerPointInvocation struct {
	Parameters struct {
		Ident1 *string
	}
	Results struct {
		Ident2 int
	}
}

// NewPointerPointInvocation creates a new instance of PointerPointInvocation
func NewPointerPointInvocation(ident1 *string, ident2 int) *PointerPointInvocation {
	invocation := new(PointerPointInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2

	return invocation
}

// PointerTestingT represents the methods of "testing".T used by charlatan Fakes.  It avoids importing the testing package.
type PointerTestingT interface {
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Helper()
}

/*
FakePointer is a mock implementation of Pointer for testing.
Use it in your tests as in this example:

	package example

	func TestWithPointer(t *testing.T) {
		f := &main.FakePointer{
			PointHook: func(ident1 *string) (ident2 int) {
				// ensure parameters meet expectations, signal errors using t, etc
				return
			},
		}

		// test code goes here ...

		// assert state of FakePoint ...
		f.AssertPointCalledOnce(t)
	}

Create anonymous function implementations for only those interface methods that
should be called in the code under test.  This will force a panic if any
unexpected calls are made to FakePoint.
*/
type FakePointer struct {
	PointHook func(*string) int

	PointCalls []*PointerPointInvocation
}

// NewFakePointerDefaultPanic returns an instance of FakePointer with all hooks configured to panic
func NewFakePointerDefaultPanic() *FakePointer {
	return &FakePointer{
		PointHook: func(*string) (ident2 int) {
			panic("Unexpected call to Pointer.Point")
		},
	}
}

// NewFakePointerDefaultFatal returns an instance of FakePointer with all hooks configured to call t.Fatal
func NewFakePointerDefaultFatal(t_sym1 PointerTestingT) *FakePointer {
	return &FakePointer{
		PointHook: func(*string) (ident2 int) {
			t_sym1.Fatal("Unexpected call to Pointer.Point")
			return
		},
	}
}

// NewFakePointerDefaultError returns an instance of FakePointer with all hooks configured to call t.Error
func NewFakePointerDefaultError(t_sym2 PointerTestingT) *FakePointer {
	return &FakePointer{
		PointHook: func(*string) (ident2 int) {
			t_sym2.Error("Unexpected call to Pointer.Point")
			return
		},
	}
}

func (f *FakePointer) Reset() {
	f.PointCalls = []*PointerPointInvocation{}
}

func (f_sym3 *FakePointer) Point(ident1 *string) (ident2 int) {
	if f_sym3.PointHook == nil {
		panic("Pointer.Point() called but FakePointer.PointHook is nil")
	}

	invocation_sym3 := new(PointerPointInvocation)
	f_sym3.PointCalls = append(f_sym3.PointCalls, invocation_sym3)

	invocation_sym3.Parameters.Ident1 = ident1

	ident2 = f_sym3.PointHook(ident1)

	invocation_sym3.Results.Ident2 = ident2

	return
}

// SetPointStub configures Pointer.Point to always return the given values
func (f_sym4 *FakePointer) SetPointStub(ident2 int) {
	f_sym4.PointHook = func(*string) int {
		return ident2
	}
}

// SetPointInvocation configures Pointer.Point to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym5 *FakePointer) SetPointInvocation(calls_sym5 []*PointerPointInvocation, fallback_sym5 func() int) {
	f_sym5.PointHook = func(ident1 *string) (ident2 int) {
		for _, call_sym5 := range calls_sym5 {
			if reflect.DeepEqual(call_sym5.Parameters.Ident1, ident1) {
				ident2 = call_sym5.Results.Ident2

				return
			}
		}

		return fallback_sym5()
	}
}

// PointCalled returns true if FakePointer.Point was called
func (f *FakePointer) PointCalled() bool {
	return len(f.PointCalls) != 0
}

// AssertPointCalled calls t.Error if FakePointer.Point was not called
func (f *FakePointer) AssertPointCalled(t PointerTestingT) {
	t.Helper()
	if len(f.PointCalls) == 0 {
		t.Error("FakePointer.Point not called, expected at least one")
	}
}

// PointNotCalled returns true if FakePointer.Point was not called
func (f *FakePointer) PointNotCalled() bool {
	return len(f.PointCalls) == 0
}

// AssertPointNotCalled calls t.Error if FakePointer.Point was called
func (f *FakePointer) AssertPointNotCalled(t PointerTestingT) {
	t.Helper()
	if len(f.PointCalls) != 0 {
		t.Error("FakePointer.Point called, expected none")
	}
}

// PointCalledOnce returns true if FakePointer.Point was called exactly once
func (f *FakePointer) PointCalledOnce() bool {
	return len(f.PointCalls) == 1
}

// AssertPointCalledOnce calls t.Error if FakePointer.Point was not called exactly once
func (f *FakePointer) AssertPointCalledOnce(t PointerTestingT) {
	t.Helper()
	if len(f.PointCalls) != 1 {
		t.Errorf("FakePointer.Point called %d times, expected 1", len(f.PointCalls))
	}
}

// PointCalledN returns true if FakePointer.Point was called at least n times
func (f *FakePointer) PointCalledN(n int) bool {
	return len(f.PointCalls) >= n
}

// AssertPointCalledN calls t.Error if FakePointer.Point was called less than n times
func (f *FakePointer) AssertPointCalledN(t PointerTestingT, n int) {
	t.Helper()
	if len(f.PointCalls) < n {
		t.Errorf("FakePointer.Point called %d times, expected >= %d", len(f.PointCalls), n)
	}
}

// PointCalledWith returns true if FakePointer.Point was called with the given values
func (f_sym6 *FakePointer) PointCalledWith(ident1 *string) bool {
	for _, call_sym6 := range f_sym6.PointCalls {
		if reflect.DeepEqual(call_sym6.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertPointCalledWith calls t.Error if FakePointer.Point was not called with the given values
func (f_sym7 *FakePointer) AssertPointCalledWith(t PointerTestingT, ident1 *string) {
	t.Helper()
	var found_sym7 bool
	for _, call_sym7 := range f_sym7.PointCalls {
		if reflect.DeepEqual(call_sym7.Parameters.Ident1, ident1) {
			found_sym7 = true
			break
		}
	}

	if !found_sym7 {
		t.Error("FakePointer.Point not called with expected parameters")
	}
}

// PointCalledOnceWith returns true if FakePointer.Point was called exactly once with the given values
func (f_sym8 *FakePointer) PointCalledOnceWith(ident1 *string) bool {
	var count_sym8 int
	for _, call_sym8 := range f_sym8.PointCalls {
		if reflect.DeepEqual(call_sym8.Parameters.Ident1, ident1) {
			count_sym8++
		}
	}

	return count_sym8 == 1
}

// AssertPointCalledOnceWith calls t.Error if FakePointer.Point was not called exactly once with the given values
func (f_sym9 *FakePointer) AssertPointCalledOnceWith(t PointerTestingT, ident1 *string) {
	t.Helper()
	var count_sym9 int
	for _, call_sym9 := range f_sym9.PointCalls {
		if reflect.DeepEqual(call_sym9.Parameters.Ident1, ident1) {
			count_sym9++
		}
	}

	if count_sym9 != 1 {
		t.Errorf("FakePointer.Point called %d times with expected parameters, expected one", count_sym9)
	}
}

// PointResultsForCall returns the result values for the first call to FakePointer.Point with the given values
func (f_sym10 *FakePointer) PointResultsForCall(ident1 *string) (ident2 int, found_sym10 bool) {
	for _, call_sym10 := range f_sym10.PointCalls {
		if reflect.DeepEqual(call_sym10.Parameters.Ident1, ident1) {
			ident2 = call_sym10.Results.Ident2
			found_sym10 = true
			break
		}
	}

	return
}
